// <auto-generated />
using System;
using FormUpAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FormUpAPI.Migrations
{
    [DbContext(typeof(FormUpDbContext))]
    partial class FormUpDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FormUpAPI.Models.ExamSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int>("FormId")
                        .HasColumnType("int")
                        .HasColumnName("form_id");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("datetime")
                        .HasColumnName("last_seen_at");

                    b.Property<int?>("RespondentId")
                        .HasColumnType("int")
                        .HasColumnName("respondent_id");

                    b.Property<string>("RespondentName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("respondent_name");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("session_id");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("started_at");

                    b.Property<int?>("SubmittedResponseId")
                        .HasColumnType("int")
                        .HasColumnName("submitted_response_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("PK__ExamSession__3213E83F0D306CE");

                    b.HasIndex("RespondentId");

                    b.HasIndex("SubmittedResponseId");

                    b.HasIndex(new[] { "FormId", "LastSeenAt" }, "IX__ExamSession__form_lastseen");

                    b.HasIndex(new[] { "FormId", "SessionId" }, "UQ__ExamSession__Form_Session")
                        .IsUnique();

                    b.ToTable("ExamSession", (string)null);
                });

            modelBuilder.Entity("FormUpAPI.Models.ExamViolationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int>("ExamSessionId")
                        .HasColumnType("int")
                        .HasColumnName("exam_session_id");

                    b.Property<DateTime?>("OccurredAt")
                        .HasColumnType("datetime")
                        .HasColumnName("occurred_at");

                    b.Property<int?>("ResponseId")
                        .HasColumnType("int")
                        .HasColumnName("response_id");

                    b.Property<string>("ViolationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("violation_type");

                    b.HasKey("Id")
                        .HasName("PK__ExamViolationLog__3213E83F0D306CF");

                    b.HasIndex(new[] { "ResponseId" }, "IX__ExamViolationLog__response_id");

                    b.HasIndex(new[] { "ExamSessionId" }, "IX__ExamViolationLog__session_id");

                    b.ToTable("ExamViolationLog", (string)null);
                });

            modelBuilder.Entity("FormUpAPI.Models.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("description");

                    b.Property<int>("FormId")
                        .HasColumnType("int")
                        .HasColumnName("form_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("reason");

                    b.Property<int?>("ResponseId")
                        .HasColumnType("int")
                        .HasColumnName("response_id");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK__Feedback__3213E83F3D69895B");

                    b.HasIndex(new[] { "FormId" }, "IX__Feedback__form_id");

                    b.HasIndex(new[] { "ResponseId" }, "IX__Feedback__response_id");

                    b.HasIndex(new[] { "UserId" }, "IX__Feedback__user_id");

                    b.ToTable("Feedback", (string)null);
                });

            modelBuilder.Entity("FormUpAPI.Models.Form", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BannerImage")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("banner_image");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("DescriptionFormat")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("description_format");

                    b.Property<string>("FormLink")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("form_link");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("status_id");

                    b.Property<DateTime?>("TakenDownAt")
                        .HasColumnType("datetime")
                        .HasColumnName("taken_down_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK__Form__3213E83F3D69895B");

                    b.HasIndex("StatusId");

                    b.HasIndex(new[] { "UserId", "DeletedAt" }, "IX__Form__user_deleted");

                    b.HasIndex(new[] { "FormLink" }, "UQ__Form__12EAC3A5F2FF2D7C")
                        .IsUnique();

                    b.ToTable("Form", (string)null);
                });

            modelBuilder.Entity("FormUpAPI.Models.FormAttemptAllowance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int>("ExtraAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("extra_attempts");

                    b.Property<int>("FormId")
                        .HasColumnType("int")
                        .HasColumnName("form_id");

                    b.Property<bool>("IsReopened")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_reopened");

                    b.Property<int?>("RespondentId")
                        .HasColumnType("int")
                        .HasColumnName("respondent_id");

                    b.Property<string>("RespondentName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("respondent_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("RespondentId");

                    b.HasIndex(new[] { "FormId", "RespondentName" }, "IX__FormAttemptAllowance__form_name");

                    b.HasIndex(new[] { "FormId", "RespondentId" }, "IX__FormAttemptAllowance__form_user");

                    b.ToTable("FormAttemptAllowance", (string)null);
                });

            modelBuilder.Entity("FormUpAPI.Models.FormSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("AutoSubmitOnTabSwitch")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("auto_submit_on_tab_switch");

                    b.Property<DateTime?>("CloseFormTime")
                        .HasColumnType("datetime")
                        .HasColumnName("close_form_time");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<bool?>("DetectTabSwitch")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("detect_tab_switch");

                    b.Property<bool?>("DisableCopyPaste")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("disable_copy_paste");

                    b.Property<int>("FormId")
                        .HasColumnType("int")
                        .HasColumnName("form_id");

                    b.Property<string>("FormToken")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("form_token");

                    b.Property<int>("FormTypeId")
                        .HasColumnType("int")
                        .HasColumnName("form_type_id");

                    b.Property<bool?>("IsExamMode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_exam_mode");

                    b.Property<int?>("MaxTabSwitch")
                        .HasColumnType("int")
                        .HasColumnName("max_tab_switch");

                    b.Property<bool?>("OneResponse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("one_response");

                    b.Property<DateTime?>("OpenFormTime")
                        .HasColumnType("datetime")
                        .HasColumnName("open_form_time");

                    b.Property<bool?>("RandomizeQuestions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("randomize_questions");

                    b.Property<bool?>("RequiredLogin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("required_login");

                    b.Property<bool?>("ShowScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("show_score");

                    b.Property<string>("ThemeBackgroundColor")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("theme_background_color");

                    b.Property<string>("ThemeConfig")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("theme_config");

                    b.Property<string>("ThemePrimaryColor")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("theme_primary_color");

                    b.Property<int?>("TimerDuration")
                        .HasColumnType("int")
                        .HasColumnName("timer_duration");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("PK__FormSett__3213E83F0D306CE3");

                    b.HasIndex("FormTypeId");

                    b.HasIndex(new[] { "FormId" }, "UQ__FormSett__190E16C8852D4A97")
                        .IsUnique();

                    b.ToTable("FormSetting", (string)null);
                });

            modelBuilder.Entity("FormUpAPI.Models.FormStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("PK__FormStat__3213E83FE1FFAC60");

                    b.ToTable("FormStatus", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Status = "Draft"
                        },
                        new
                        {
                            Id = 2,
                            Status = "Published"
                        },
                        new
                        {
                            Id = 3,
                            Status = "Closed"
                        });
                });

            modelBuilder.Entity("FormUpAPI.Models.FormType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("PK__FormType__3213E83FE1FFAC61");

                    b.ToTable("FormType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Type = "Single Page"
                        },
                        new
                        {
                            Id = 2,
                            Type = "Multi Page"
                        });
                });

            modelBuilder.Entity("FormUpAPI.Models.GeminiApiKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("api_key");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("code_hash");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Label")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("label");

                    b.Property<int>("RedeemedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("redeemed_count");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("GeminiApiKey", (string)null);
                });

            modelBuilder.Entity("FormUpAPI.Models.GeminiApiKeyRedemption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KeyId")
                        .HasColumnType("int")
                        .HasColumnName("key_id");

                    b.Property<DateTime?>("RedeemedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("redeemed_at")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "KeyId", "UserId" }, "IX__GeminiApiKeyRedemption__key_user")
                        .IsUnique();

                    b.ToTable("GeminiApiKeyRedemption", (string)null);
                });

            modelBuilder.Entity("FormUpAPI.Models.OptionQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<bool?>("IsCorrect")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_correct");

                    b.Property<string>("OptionImage")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("option_image");

                    b.Property<int>("OptionOrder")
                        .HasColumnType("int")
                        .HasColumnName("option_order");

                    b.Property<string>("OptionText")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("option_text");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int")
                        .HasColumnName("question_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("PK__OptionQu__3213E83F6E9D36B3");

                    b.HasIndex("QuestionId");

                    b.ToTable("OptionQuestion", (string)null);
                });

            modelBuilder.Entity("FormUpAPI.Models.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit")
                        .HasColumnName("is_used");

                    b.Property<string>("Otp")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("otp");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId" }, "IX__PasswordResetToken__user_id");

                    b.ToTable("PasswordResetToken", (string)null);
                });

            modelBuilder.Entity("FormUpAPI.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CorrectAnswer")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("correct_answer");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("deleted_at");

                    b.Property<int>("FormId")
                        .HasColumnType("int")
                        .HasColumnName("form_id");

                    b.Property<bool?>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_required");

                    b.Property<int?>("Points")
                        .HasColumnType("int")
                        .HasColumnName("points");

                    b.Property<string>("Question1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("question");

                    b.Property<string>("QuestionAudio")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("question_audio");

                    b.Property<string>("QuestionFormat")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("question_format");

                    b.Property<string>("QuestionImage")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("question_image");

                    b.Property<int>("QuestionOrder")
                        .HasColumnType("int")
                        .HasColumnName("question_order");

                    b.Property<bool?>("RandomizeOptions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("randomize_options");

                    b.Property<int>("TypeId")
                        .HasColumnType("int")
                        .HasColumnName("type_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("PK__Question__3213E83F23B2E249");

                    b.HasIndex("TypeId");

                    b.HasIndex(new[] { "FormId", "DeletedAt" }, "IX__Question__form_deleted");

                    b.ToTable("Question", (string)null);
                });

            modelBuilder.Entity("FormUpAPI.Models.QuestionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("PK__Question__3213E83F5563C7FF");

                    b.ToTable("QuestionType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Type = "Essay"
                        },
                        new
                        {
                            Id = 2,
                            Type = "Multiple Choice"
                        },
                        new
                        {
                            Id = 3,
                            Type = "Checkbox"
                        },
                        new
                        {
                            Id = 4,
                            Type = "Date Time"
                        },
                        new
                        {
                            Id = 5,
                            Type = "True False"
                        });
                });

            modelBuilder.Entity("FormUpAPI.Models.RegistrationOtp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit")
                        .HasColumnName("is_used");

                    b.Property<string>("Otp")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("otp");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Email" }, "IX__RegistrationOtp__email");

                    b.ToTable("RegistrationOtp", (string)null);
                });

            modelBuilder.Entity("FormUpAPI.Models.RespondentAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnswerValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("answer_value");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<bool?>("IsCorrectOverride")
                        .HasColumnType("bit")
                        .HasColumnName("is_correct_override");

                    b.Property<double?>("ManualScore")
                        .HasColumnType("float")
                        .HasColumnName("manual_score");

                    b.Property<int?>("OptionId")
                        .HasColumnType("int")
                        .HasColumnName("option_id");

                    b.Property<string>("OverrideNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("override_note");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int")
                        .HasColumnName("question_id");

                    b.Property<int>("ResponseId")
                        .HasColumnType("int")
                        .HasColumnName("response_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("PK__Responde__3213E83F515219BC");

                    b.HasIndex("OptionId");

                    b.HasIndex(new[] { "QuestionId" }, "IX__RespondentAnswer__question_id");

                    b.HasIndex(new[] { "ResponseId" }, "IX__RespondentAnswer__response_id");

                    b.ToTable("RespondentAnswer", (string)null);
                });

            modelBuilder.Entity("FormUpAPI.Models.Response", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int>("FormId")
                        .HasColumnType("int")
                        .HasColumnName("form_id");

                    b.Property<int?>("RespondentId")
                        .HasColumnType("int")
                        .HasColumnName("respondent_id");

                    b.Property<string>("RespondentName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("respondent_name");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("status_id");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("submitted_at");

                    b.Property<int?>("TabSwitchCount")
                        .HasColumnType("int")
                        .HasColumnName("tab_switch_count");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("PK__Response__3213E83F3BCBD39E");

                    b.HasIndex("StatusId");

                    b.HasIndex(new[] { "FormId", "SubmittedAt" }, "IX__Response__form_submitted");

                    b.HasIndex(new[] { "RespondentId" }, "IX__Response__respondent_id");

                    b.ToTable("Response", (string)null);
                });

            modelBuilder.Entity("FormUpAPI.Models.ResponseStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("PK__Response__3213E83F3C285B45");

                    b.ToTable("ResponseStatus", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Status = "new"
                        },
                        new
                        {
                            Id = 5,
                            Status = "submitted"
                        });
                });

            modelBuilder.Entity("FormUpAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("Birthdate")
                        .HasColumnType("date")
                        .HasColumnName("birthdate");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("fullname");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("ProfileImage")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("profile_image");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("USER")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("PK__User__3213E83F660F0712");

                    b.HasIndex(new[] { "Email" }, "UQ__User__AB6E6164EA4F3FA3")
                        .IsUnique();

                    b.HasIndex(new[] { "Username" }, "UQ__User__F3DBC572C6AD5753")
                        .IsUnique()
                        .HasFilter("[username] IS NOT NULL");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("FormUpAPI.Models.ExamSession", b =>
                {
                    b.HasOne("FormUpAPI.Models.Form", "Form")
                        .WithMany()
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ExamSession__form_id");

                    b.HasOne("FormUpAPI.Models.User", "Respondent")
                        .WithMany()
                        .HasForeignKey("RespondentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__ExamSession__respondent_id");

                    b.HasOne("FormUpAPI.Models.Response", "SubmittedResponse")
                        .WithMany("ExamSessions")
                        .HasForeignKey("SubmittedResponseId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__ExamSession__response_id");

                    b.Navigation("Form");

                    b.Navigation("Respondent");

                    b.Navigation("SubmittedResponse");
                });

            modelBuilder.Entity("FormUpAPI.Models.ExamViolationLog", b =>
                {
                    b.HasOne("FormUpAPI.Models.ExamSession", "ExamSession")
                        .WithMany("ViolationLogs")
                        .HasForeignKey("ExamSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ExamViolationLog__session_id");

                    b.HasOne("FormUpAPI.Models.Response", "Response")
                        .WithMany("ExamViolationLogs")
                        .HasForeignKey("ResponseId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__ExamViolationLog__response_id");

                    b.Navigation("ExamSession");

                    b.Navigation("Response");
                });

            modelBuilder.Entity("FormUpAPI.Models.Feedback", b =>
                {
                    b.HasOne("FormUpAPI.Models.Form", "Form")
                        .WithMany()
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Feedback_Form");

                    b.HasOne("FormUpAPI.Models.Response", "Response")
                        .WithMany()
                        .HasForeignKey("ResponseId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Feedback_Response");

                    b.HasOne("FormUpAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Feedback_User");

                    b.Navigation("Form");

                    b.Navigation("Response");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FormUpAPI.Models.Form", b =>
                {
                    b.HasOne("FormUpAPI.Models.FormStatus", "Status")
                        .WithMany("Forms")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK__Form__status_id__49C3F6B7");

                    b.HasOne("FormUpAPI.Models.User", "User")
                        .WithMany("Forms")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Form__user_id__48CFD27E");

                    b.Navigation("Status");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FormUpAPI.Models.FormAttemptAllowance", b =>
                {
                    b.HasOne("FormUpAPI.Models.Form", "Form")
                        .WithMany()
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FormUpAPI.Models.User", "Respondent")
                        .WithMany()
                        .HasForeignKey("RespondentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Form");

                    b.Navigation("Respondent");
                });

            modelBuilder.Entity("FormUpAPI.Models.FormSetting", b =>
                {
                    b.HasOne("FormUpAPI.Models.Form", "Form")
                        .WithOne("FormSetting")
                        .HasForeignKey("FormUpAPI.Models.FormSetting", "FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__FormSetti__form___5165187F");

                    b.HasOne("FormUpAPI.Models.FormType", "FormType")
                        .WithMany("FormSettings")
                        .HasForeignKey("FormTypeId")
                        .IsRequired();

                    b.Navigation("Form");

                    b.Navigation("FormType");
                });

            modelBuilder.Entity("FormUpAPI.Models.GeminiApiKeyRedemption", b =>
                {
                    b.HasOne("FormUpAPI.Models.GeminiApiKey", "Key")
                        .WithMany("Redemptions")
                        .HasForeignKey("KeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FormUpAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Key");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FormUpAPI.Models.OptionQuestion", b =>
                {
                    b.HasOne("FormUpAPI.Models.Question", "Question")
                        .WithMany("OptionQuestions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__OptionQue__quest__5CD6CB2B");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("FormUpAPI.Models.PasswordResetToken", b =>
                {
                    b.HasOne("FormUpAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FormUpAPI.Models.Question", b =>
                {
                    b.HasOne("FormUpAPI.Models.Form", "Form")
                        .WithMany("Questions")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Question__form_i__571DF1D5");

                    b.HasOne("FormUpAPI.Models.QuestionType", "Type")
                        .WithMany("Questions")
                        .HasForeignKey("TypeId")
                        .IsRequired()
                        .HasConstraintName("FK__Question__type_i__5812160E");

                    b.Navigation("Form");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("FormUpAPI.Models.RespondentAnswer", b =>
                {
                    b.HasOne("FormUpAPI.Models.OptionQuestion", "Option")
                        .WithMany("RespondentAnswers")
                        .HasForeignKey("OptionId")
                        .HasConstraintName("FK__Responden__optio__68487DD7");

                    b.HasOne("FormUpAPI.Models.Question", "Question")
                        .WithMany("RespondentAnswers")
                        .HasForeignKey("QuestionId")
                        .IsRequired()
                        .HasConstraintName("FK__Responden__quest__6754599E");

                    b.HasOne("FormUpAPI.Models.Response", "Response")
                        .WithMany("RespondentAnswers")
                        .HasForeignKey("ResponseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Responden__respo__66603565");

                    b.Navigation("Option");

                    b.Navigation("Question");

                    b.Navigation("Response");
                });

            modelBuilder.Entity("FormUpAPI.Models.Response", b =>
                {
                    b.HasOne("FormUpAPI.Models.Form", "Form")
                        .WithMany("Responses")
                        .HasForeignKey("FormId")
                        .IsRequired()
                        .HasConstraintName("FK__Response__form_i__60A75C0F");

                    b.HasOne("FormUpAPI.Models.User", "Respondent")
                        .WithMany("Responses")
                        .HasForeignKey("RespondentId")
                        .HasConstraintName("FK__Response__respon__619B8048");

                    b.HasOne("FormUpAPI.Models.ResponseStatus", "Status")
                        .WithMany("Responses")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK__Response__status__628FA481");

                    b.Navigation("Form");

                    b.Navigation("Respondent");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("FormUpAPI.Models.ExamSession", b =>
                {
                    b.Navigation("ViolationLogs");
                });

            modelBuilder.Entity("FormUpAPI.Models.Form", b =>
                {
                    b.Navigation("FormSetting");

                    b.Navigation("Questions");

                    b.Navigation("Responses");
                });

            modelBuilder.Entity("FormUpAPI.Models.FormStatus", b =>
                {
                    b.Navigation("Forms");
                });

            modelBuilder.Entity("FormUpAPI.Models.FormType", b =>
                {
                    b.Navigation("FormSettings");
                });

            modelBuilder.Entity("FormUpAPI.Models.GeminiApiKey", b =>
                {
                    b.Navigation("Redemptions");
                });

            modelBuilder.Entity("FormUpAPI.Models.OptionQuestion", b =>
                {
                    b.Navigation("RespondentAnswers");
                });

            modelBuilder.Entity("FormUpAPI.Models.Question", b =>
                {
                    b.Navigation("OptionQuestions");

                    b.Navigation("RespondentAnswers");
                });

            modelBuilder.Entity("FormUpAPI.Models.QuestionType", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("FormUpAPI.Models.Response", b =>
                {
                    b.Navigation("ExamSessions");

                    b.Navigation("ExamViolationLogs");

                    b.Navigation("RespondentAnswers");
                });

            modelBuilder.Entity("FormUpAPI.Models.ResponseStatus", b =>
                {
                    b.Navigation("Responses");
                });

            modelBuilder.Entity("FormUpAPI.Models.User", b =>
                {
                    b.Navigation("Forms");

                    b.Navigation("Responses");
                });
#pragma warning restore 612, 618
        }
    }
}
